### ISSUE TITLE
How to increase quality?

### ISSUE THREAD

**Issue by platform-kit** [KevinWang676/Bark-Voice-Cloning#1]
Hey, @KevinWang676, great work on this repo.  

If I want to increase the quality what's the best way to go about that?

I imagine the number of steps that are used during both training and inference must be stored in some variable somewhere. Can you point me to it?

Or maybe there's another obvious solution?

**Comment by KevinWang676** [comment]
Hi, thanks for your interest. The implementation of Bark Voice Cloning is based on this [repo](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer). You can check it out for more details. The easiest way to increase the quality is to upload better quality audio as input. Ideally the input audio should be more than 10 seconds long.
