### ISSUE TITLE
大哥别骗人好不好

### ISSUE THREAD

**Issue by 448486810** [KevinWang676/Bark-Voice-Cloning#11]
明明在huggingface用的是人家的gui，把人骗过来也不说明一下[GUI地址](https://github.com/C0untFloyd/bark-gui)

**Comment by KevinWang676** [comment]
本仓库及配套的HuggingFace程序均在最开始创建时已经注明了出处，请仔细阅读本仓库！

![image](https://github.com/KevinWang676/Bark-Voice-Cloning/assets/126712357/aac06cf8-cd80-4551-8eff-de5449fe61ca)

![image](https://github.com/KevinWang676/Bark-Voice-Cloning/assets/126712357/f6c8dab4-cc52-4da0-a8ad-5a991d608725)
