### ISSUE TITLE
训练前的预处理这一步卡住，最后一行信息提示text_preprocess: text file lines must be equals to 142

### ISSUE THREAD

**Issue by DreamCloudWalker** [KevinWang676/Bark-Voice-Cloning#12]
ret, report = run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.5")
这一步卡住很长时间都不结束。如果强行结束开始训练会报错：
FileNotFoundError: [Errno 2] No such file or directory: '/content/output_training_data/prosody/prosody.txt'

**Comment by KevinWang676** [comment]
需要用GPU环境，如果是一分钟的素材，这一步的运行时间大概是五分钟。可能是你的素材时间太长了或者没有使用GPU

**Comment by DreamCloudWalker** [comment]
搞好了，谢谢。是用的GPU，可能用的不是专业版的Colab，比较慢，再加上我的素材超过了1分钟。执行了比较长的时间。
