### ISSUE TITLE
python app.py 想在另一台配置高的机器上运行 在笔记本上访问 如何指定IP呀大佬？

### ISSUE THREAD

**Issue by ZenXir** [KevinWang676/Bark-Voice-Cloning#21]
现在运行是默认的 127.0.0.1 默认IP，如何指定IP和端口呀

**Comment by whao** [comment]
@ZenXir Hey 您好，想请问一下你是修改的哪个参数呀？

**Comment by KevinWang676** [comment]
@whao 可以在 `app.launch()`里添加`server_port=`来设定IP地址
