### ISSUE TITLE
全是BUG

### ISSUE THREAD

**Issue by Ibuprofenighty** [KevinWang676/Bark-Voice-Cloning#31]
在Colab上跑 autolabel,

先是找不到 temp.wav file, 撕源码 发现压根就没有存储过temp.wav的code(只有起了这个名字string).

改了这个后, 终于走完cut_wav和prosody也出来了 然后继续报错 'can not find the file of sox'. 真的头大.

由于autolabel的部份依赖(nls-fa)只能由linux系统下安装. 我现在还只能在colab上撕源码.

老哥你有没有啥建议呀 555

**Comment by KevinWang676** [comment]
因为KANTTS需要严苛的环境配置，建议还是在Colab中运行，但可能也会遇到不稳定的问题。可以关注一下本项目中最新的VALL-E X声音克隆，支持中日英三语的拟声
