### ISSUE TITLE
/content/output_training_data/wav_pre/temp.wav

### ISSUE THREAD

**Issue by JavaAndPython55** [KevinWang676/Bark-Voice-Cloning#41]
按照你的一步步来的，结果到这里没有这个temp.wav文件提示，报错
<img width="719" alt="image" src="https://github.com/KevinWang676/Bark-Voice-Cloning/assets/34533090/1eb0ddb9-795f-4068-a375-9b29dc046a55">

**Comment by JavaAndPython55** [comment]
执行这段代码的时候input_wav = "./test_wavs/"
output_data = "./output_training_data/"

ret, report = run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.7")提示

**Comment by JavaAndPython55** [comment]
2023-09-06 07:29:24,634 - modelscope - INFO - Use user-specified model revision: v1.0.7
--- Remove /content/output_training_data/paragraph/prosody folder!  ---
---  New folder /content/output_training_data/paragraph/prosody...  ---
---  OK  ---
---  New folder /content/output_training_data/wav...  ---
---  OK  ---
--- Remove /content/output_training_data/wav_decrease_sp folder!  ---
---  New folder /content/output_training_data/wav_decrease_sp...  ---
---  OK  ---
--- Remove /content/output_training_data/log folder!  ---
---  New folder /content/output_training_data/log...  ---
---  OK  ---
2023-09-06 07:29:39
TTS-AutoLabel version: 1.1.8
TTS-AutoLabel resource path: /root/.cache/modelscope/hub/damo/speech_ptts_autolabel_16k/model
Target sampling rate: 16000
Input wav dir: /content/test_wavs
Output data dir: /content/output_training_data
wav_preprocess start...
---  There is this folder!  ---
  0%|          | 0/35 [00:00<?, ?it/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-12-2b55d21d2966>](https://localhost:8080/#) in <cell line: 4>()
      2 output_data = "./output_training_data/"
      3 
----> 4 ret, report = run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.7")

3 frames
[/usr/local/lib/python3.10/dist-packages/tts_autolabel/resample_16.py](https://localhost:8080/#) in resample(src_wav_dir, tgt_wav_dir, tgt_sr)
     58                     logging.info(cmdline)
     59                 os.system(cmdline)
---> 60                 os.remove(temp_file)
     61 
     62 

FileNotFoundError: [Errno 2] No such file or directory: '/content/output_training_data/wav_pre/temp.wav'

**Comment by JavaAndPython55** [comment]
解决了，这个必须要在pytorch的那个目录里面创建文件夹和执行

**Comment by venxzw** [comment]
@JavaAndPython55 请问是创建那三个文件的时候需要进入到pytorch_wavelets这个文件夹里吗？

**Comment by luhairong11** [comment]
我也遇到这个问题，工程下没有pytorch的目录呀
