### ISSUE TITLE
在TTS页面写的是中文，说的是英文，和写的中文内容毫无关系

### ISSUE THREAD

**Issue by heiheiheibj** [KevinWang676/Bark-Voice-Cloning#45]
我在CLONE VOICE页面训练了声音也生成了NPZ文件
在TTS页面的INPUT TEXT中随便输入了一段中文，但讲的话是英文，today。。。。
如果把voice类型由file改为none，是按输入的文本念的中文，但是发英象是老外说中文一样，像川普的口音
另外请问下，项目中有没有地方能上传NPZ文件，这样就不用每次重新练，直接上传NPZ然后写入新要发声的文字内容
谢谢
![image](https://github.com/KevinWang676/Bark-Voice-Cloning/assets/6910198/2b1b836a-e94a-4490-a3c6-4c76d3fa6589)

**Comment by KevinWang676** [comment]
没错，因为声音克隆功能只支持英文，不能克隆中文。如果想自己上传npz文件，需要修改一下代码，对应位置改成`npz_file = gr.File(label=".npz file")`

**Comment by heiheiheibj** [comment]
好的谢谢。。
