### ISSUE TITLE
初始化标注模型失败run_auto_label，prepare tts engine failed

### ISSUE THREAD

**Issue by stevin-dong** [KevinWang676/Bark-Voice-Cloning#63]
初始化标注模型失败：
run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.7",
                                 resource_model_id="models/damo/speech_ptts_autolabel_16k")
错误信息：                                 
load leagacy transf breakmodel
text.cc: festival_Text_init
prepare tts engine failed
lang type empty or not init
INFO:root:Text to label start...
  0%|                                                                                                                                                                          | 0/44 [00:00<?, ?it/s]not init
do general frd process failed...

其中speech_ptts_autolabel_16k我是从autodl的镜像中复制过来的
请问大佬这个错误怎么破？

**Comment by KevinWang676** [comment]
应该是某几个package不兼容，版本出来问题

**Comment by stevin-dong** [comment]
> 应该是某几个package不兼容，版本出来问题

我重新安装了几次还是这样，安装过程没有报错，不知道从何下手去解决了，系统是ubuntu20.04，大佬再帮分析一下有可能是哪些包不兼容，感谢！

**Comment by stevin-dong** [comment]
> > 应该是某几个package不兼容，版本出来问题
> 
> 我重新安装了几次还是这样，安装过程没有报错，不知道从何下手去解决了，系统是ubuntu20.04，大佬再帮分析一下有可能是哪些包不兼容，感谢！

已经解决了，谢谢！
