### ISSUE TITLE
在 colab上运行遇到 AssertionError: libcuda.so cannot found!

### ISSUE THREAD

**Issue by Xuenew** [KevinWang676/Bark-Voice-Cloning#74]
split_long_audio(whisper_model, "filename.wav", "test", "dataset_raw") # 请在{filename}处填写您上传的wav文件名

Transcribing file 0: 'filename.wav' to segments...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-6-18509f480016>](https://localhost:8080/#) in <cell line: 1>()
----> 1 split_long_audio(whisper_model, "filename.wav", "test", "dataset_raw") # 请在{filename}处填写您上传的wav文件名

9 frames
<string> in kernel(y, x, x_stride, y_stride, BLOCK_SIZE, grid, num_warps, num_stages, extern_libs, stream, warmup, device, device_type)

[/usr/local/lib/python3.10/dist-packages/triton/common/build.py](https://localhost:8080/#) in libcuda_dirs()
     28         msg += 'Possible files are located at %s.' % str(locs)
     29         msg += 'Please create a symlink of libcuda.so to any of the file.'
---> 30     assert any(os.path.exists(os.path.join(path, 'libcuda.so')) for path in dirs), msg
     31     return dirs
     32 

AssertionError: libcuda.so cannot found!

您好，请问遇到这个错误我该怎么处理？我用的是T4 GPU

**Comment by Xuenew** [comment]
😭 用阿里的 在就每次一到这里就会报错要重启
input_wav = "./test_wavs/"
output_data = "./output_training_data/"

ret, report = run_auto_label(input_wav=input_wav, work_dir=output_data, resource_revision="v1.0.5")
-----------------------------------------------
Kernel Restarting
The kernel for 阿里云笔记本训练.ipynb appears to have died. It will restart automatically.

**Comment by KevinWang676** [comment]
需要更新成 `resource_revision='v1.0.7'`

**Comment by Xuenew** [comment]
https://modelscope.cn/studios/damo/personal_tts/summary

在这里我联系了可以了，虽然有点小麻烦，照着流程是可以完成的 😁
